### ISSUE TITLE
methodQueue - enables broadcasting before datalayer is ready 

### ISSUE THREAD

**Issue by mspoerer** [ryx/datalayer.js#14]
The methodQueue extension enables broadcasting functionality before the dataylayer and its plugins are ready. This and the condition, that the 'not yet initialized' plugins can already listen to events, lead to unexpected behaviour. Especially, if the plugin initialisation, is somehow crucial for further event processing.  

**Expected behavior**
The methodQueue extension should enable broadcasting functionality after datalayer and its plugins are initialised.

**Comment by ryx** [comment]
Yes, it might be sufficient to just wrap the call to `createMethodQueueHandler` in a `datalayer.whenReady()` Promise, and let it wait for the datalayer to become ready before executing the queued calls. We _could_ add a dedicated `afterInitialize` extension hook, but it seems a bit redundant (and overengineered) in that certain case.

**Comment by ryx** [comment]
Should be resolved with 0.0.27 release: https://github.com/ryx/datalayer.js/releases/tag/v0.0.27

**Comment by ryx** [comment]
I finally decided to switch to an `afterInitialize` hook instead of promises for applying the methodQueue, because it better separates (internal) hooks from the public (3rd party) Promise-interface. Will be available with v0.0.28
